apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: myapp:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        volumeMounts:
        - name: app-config
          mountPath: /etc/config
        - name: app-data
          mountPath: /var/lib/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
      volumes:
      - name: app-config
        configMap:
          name: app-config
      - name: app-data
        persistentVolumeClaim:
          claimName: app-pvc
